name: Deploy Develop Branch

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to 'develop' folder
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          branch: main
          target-folder: develop
          clean: true
          force: false
